[package]
name = "Exotic_Primitives_VRF_Activity"
version = "0.1.0"
edition = "2021"

[dependencies]
merlin = "3.0.0"
rand = "0.8.5"
rand_core = "0.6.4"
schnorrkel = "0.11.4"
sha2 = "0.10.8"
sp-core = "33.0.0"
